### ISSUE TITLE
[ws] If disconnect ws connection, you will never create a new connection

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1385] opened 2017-07-21 03:53 UTC
### Description

I disconnect ws connection and will re-connect, but ws server and client look like be hang. So I close ws client and get an error.
 

### Test Code

[/samples/websockets/WebSocketServer.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer.js)
[/samples/websockets/NodeWebSocketClient.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/NodeWebSocketClient.js)

 

### Steps to Reproduction

1. Run WebSocketServer.js on a101
2. Run NodeWebSocketClient.js on linux
3. Disconnect this ws connection
4. Re-connect ws connection
5. Close ws client
6. Check log info.
 

### Actual Result

Error info:
```
 src/zjs_event.c:358 zjs_trigger_event():
(ERROR) callback_id not found
```

### Expected Result

 Work well and can be re-connected.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 5c65f1102 | Arduino 101 | July 21, 2017 | Fail

**Comment by qiaojingx** [comment] 2017-08-03 01:43
Verified with commit 4d9b084. Still can't create a new connection after disconnect ws connection.
But no error is print now.
![selection_141](https://user-images.githubusercontent.com/19813546/28902220-342b9d30-7830-11e7-8f9d-33dfb775cc01.png)

**Comment by brianjjones** [comment] 2017-08-04 16:08
This seems to be due to websockets not handling close properly.  Its not emitting the close signal or handling it.  I'm working on a fix now.

**Comment by brianjjones** [comment] 2017-08-04 23:25
Unfortunately I still can't seem to get this working.  I altered the NodeWebSocketClient.js to  call ws.terminate() after about 10 seconds, and then create a new WebSocket connection after another 5.  It always hangs at the same spot during the second connect, zjs_web_sockets.c:220.  I suspect it may be a Zephyr bug.  Whoever looks at this next might see if there are any zephyr samples that could demonstrate being able to reconnect or have multiple clients.

**Comment by grgustaf** [comment] 2017-08-10 00:28
Looking into this bug, I found that the sample doesn't work at all on A101+Ethernet. I'm pretty sure it was working when I checked in the big event patch last week though. After lots of debugging with @jprestwo's help, it appears that adding NET_BUF_DATA_SIZE=512 like @jimmy-huang did for OCF recently fixes that. We also discovered a June 16th patch in Zephyr, right after 1.8 release, that had to do with net_pkt fragmentation, but ultimately that didn't seem to be needed.

There seems to be a bug in the net_pkt fragmentation that this exposes. Oddly it doesn't seem to happen over Bluetooth, even though it's Bluetooth that Jimmy first had the problem with in OCF code.

Something's a bit flaky; occasionally the sample won't work, and occasionally it stops at CONNECTION and doesn't get farther. But w/ just this 512 byte patch I just now ran the node code about 20 times w/o rebooting the device and it kept working. I'll get back to looking at how it works over BT tomorrow.

**Comment by qiaojingx** [comment] 2017-08-11 03:48
Verified with commit 247b51a. Websocket is able to reconnect on Arduino101 over BT.
![selection_153](https://user-images.githubusercontent.com/19813546/29200744-5b12c558-7e8a-11e7-8275-3e0f681db604.png)
Waiting for ENC28J60 Ethernet Board to verify websocket samples on Arduino101+ Ethernet.

**Closed** 2017-08-14 22:05 UTC
Labels: bug, fixed, P1

**Comment by qiaojingx** [comment] 2017-08-16 08:29
Verified with commit 212747a. This issue is not reproduced on Arduino101 over BT

**Comment by cuiyanx** [comment] 2018-01-10 01:41
Fixed and closed
