### ISSUE TITLE
[ashell] Web USB does not work with the Zephyr SDK 0.9

### ISSUE THREAD

**Issue by poussa** [01org/zephyr.js#823] opened 2017-03-13 11:53 UTC
When I build the latest master (https://github.com/01org/zephyr.js/commit/eaf24e967bd909954c20a7409be5560904f237ee) with ashell (make DEV=ashell) usign the Zephyr SDK 0.9, I don't get the USB device at all (/dev/ACM0 or /dev/cu.usbmodem0_01). When building with Zephyr SDK 0.8.2 it works fine. 

I have no idea what is going on? Can somebody else test?

@brianjjones @nagineni

**Comment by nagineni** [comment] 2017-03-13 13:06
WebUSB alone works fine, but the issue is reproducible if we build it with the ashell. Something to do with the ashell it seems.

**Comment by nagineni** [comment] 2017-03-13 13:18
Quick update: ashell with WebUSB is working for me if I disable AIO and I2C modules while building.

**Comment by brianjjones** [comment] 2017-03-13 15:58
Will test and report back.

**Comment by nagineni** [comment] 2017-03-13 16:07
I2C seems to be working after updating zephyr deps to the latest master, but AIO is still broken. I suspect this might be a zephyr upstream or SDK issue - https://jira.zephyrproject.org/browse/ZEP-1882

**Comment by nagineni** [comment] 2017-03-13 16:14
I also noticed that the issue doesn't appear if we enable debug mode by adding CONFIG_DEBUG=y in scripts/analyze.sh.

**Comment by jimmy-huang** [comment] 2017-03-15 00:09
I can reproduce this with AIO, so a bug already filed upstream, should be fixed after updating gcc from 6.2.1 to 6.3, in the mean time we can patch it with adding CONFIG_DEBUG=y if needed.

https://jira.zephyrproject.org/browse/ZEP-1882

**Comment by nagineni** [comment] 2017-03-15 16:24
Workaround is here: https://github.com/nagineni/zephyr.js/commit/e65128

**Comment by jimmy-huang** [comment] 2017-03-15 20:22
@nagineni lgtm, would you like to submit a pr? we can merge and revert it later after Zephyr fixes it.

**Comment by qiaojingx** [comment] 2017-03-17 03:17
Verified with commit 6d7a58b
Building with ashell (`make DEV=ashell`) failed using the Zephyr SDK 0.9. But, building with Zephyr SDK 0.8.2 succeed.
![selection_016](https://cloud.githubusercontent.com/assets/19813546/24027455/b37d3a08-0b02-11e7-8720-7773d9b8aeaf.png)

**Comment by qiaojingx** [comment] 2017-03-24 07:07
Verified with commit c9991f0. This issue is not reproducible.

**Closed** 2017-03-29 18:14 UTC
Labels: bug, fixed, P1, regression
