### ISSUE TITLE
[PnP] ARC RAM and ROM sample increase obviously compared with master commit 3950beb.

### ISSUE THREAD

**Issue by hanyia** [01org/zephyr.js#1160] opened 2017-05-16 01:41 UTC
update to SDK 0.9, found a new bug, detail info as below table:

Device | KPIs | ww20 master: e24821c | ww19 master: 3950beb |ww20vs ww19(%)
----|------|----|----|----
Arduino101 | Zephyr_Helloworld_ARC_RAM(Byte)  | 6712 |5592 | 20.03 
Arduino101 | Zephyr_I2C_ARC_ROM(Byte) | 20072 | 16464 | 21.91 
Arduino101 | Zephyr_I2C_ARC_RAM(Byte)  | 6848 | 5728 | 19.55 
Arduino101 | Zephyr_WebBluetoothGroveLcdDemo_ARC_ROM(Byte)  | 24436 | 20220 |20.85
Arduino101 | Zephyr_WebBluetoothGroveLcdDemo_ARC_RAM(Byte)  | 7288 | 6168 | 18.16

**Comment by jimmy-huang** [comment] 2017-05-17 18:07
This is a known issue, because to work-around the bug ZEP-1882 that AIO is broken with 0.9 SDK, we updated Zephyr to use commit that contains the patch to build ARC with -O2 instead of -Os, thus the increased ROM and RAM size.  We should be able to fix this once Zephyr released a fixed SDK.

**Comment by grgustaf** [comment] 2017-06-07 22:25
@jimmy-huang wasn't this fixed later?

**Comment by hanyia** [comment] 2017-07-11 02:34
Verify this issue on latest SDK 0.9.1, only Zephyr_WebBluetoothGroveLcdDemo_ARC_RAM KPI has meet this issue, result is 7184, has 16.47% gap. Other KPIs have fixed.

**Comment by jimmy-huang** [comment] 2017-07-31 21:07
We can probably close this as this is a duplicate of #1367

**Closed** 2017-08-14 16:59 UTC
Labels: bug, P2
