### ISSUE TITLE
ashell has parser disabled now

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#936] opened 2017-03-29 20:04 UTC
Probably some recent Makefile change messed this up and left SNAPSHOT=on or something?

**Comment by grgustaf** [comment] 2017-03-30 21:46
I should have reported what I actually saw. After building ashell, flashing, and booting, it reported an error about parser not being available or something on the secondary shell (USB0?). Then on the ACM0 if I tried to do an eval or something it would give me an error that there was no parser.

**Comment by jimmy-huang** [comment] 2017-03-30 21:55
@grgustaf works for me, if you can reproduce this, show the steps how to reproduce it, or close this issue.

**Comment by qiaojingx** [comment] 2017-04-01 07:57
Verified with commit f3d587d. This issue can be reproduced.
Steps1: 
1. `make ide`
2. `make dfu`
3. connect ashell with webide(you may met [issue104](https://github.com/01org/zephyrjs-ide/issues/104))
4. Run examples/[Blink.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/basics/Blink.js) in it.

Error got:
![selection_007](https://cloud.githubusercontent.com/assets/19813546/24576703/6b08860e-16f3-11e7-8195-e961feedff23.png)

Steps2: 
1. `make ashell`
2. `make dfu`
3. connect ashell with terminal via `screen /dev/ttyACM0 115200`
4. `acm > load test.js`
5. Input samples/[Blink.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/basics/Blink.js)  and CTRL+Z to saving
6. `acm > run test.js`

Error info as below:
ACM0:
![selection_005](https://cloud.githubusercontent.com/assets/19813546/24576688/33e315c2-16f3-11e7-8b01-a3072dd9ef7c.png)
USB0:
![selection_006](https://cloud.githubusercontent.com/assets/19813546/24576691/38cb52ca-16f3-11e7-9b63-7a57f3f2d966.png)

**Comment by grgustaf** [comment] 2017-04-04 17:18
Well, I can't reproduce it now on master or on the commit @qiaojingx listed. But yes this is exactly what I saw, I'm glad I wasn't crazy. :)

Apparently we haven't identified the exact steps to reproduce it. I'm lowering to P3 until we can find a consistent way to reproduce it.

**Comment by jimmy-huang** [comment] 2017-04-05 20:55
Looking at the makefile, it could be caused by if you first build with snapshot, then somehow you did something where you removed .snapshot.last_build file, so it mistakenly thinks that jerryscript already have parser enabled, and doesn't rebuild it,

So one way (maybe the only way) to reproduce this is:
1. make JS=Helloworld.js (or anything that uses SNAPSHOT=on)
2. make clean BOARD=linux
3. make ide

Does these steps sound like what you guys might haven done to reproduce this?

**Comment by jimmy-huang** [comment] 2017-04-05 21:09
Submitted possible fix here #974

**Comment by grgustaf** [comment] 2017-04-06 23:15
Submitted another possible fix in #986

**Closed** 2017-04-06 23:20 UTC
Labels: bug, fixed, P3, regression
