### ISSUE TITLE
[ashell] Redundant message outputs

### ISSUE THREAD

**Issue by xiaoyu3x** [01org/zephyr.js#1502] opened 2017-08-28 02:49 UTC
## Issue description
Redundant message is printed on terminal and it affect the next input.

## Test Code
[ashell](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md)

## Steps to reproduce
1. `make ROM=256 ashell; make dfu`
2. Flash ashell into 101 board, reset it and open port:
    `$ screen /dev/ttyACM0 115200`

## Actual Result
Redundant message is printed.
![selection_001](https://user-images.githubusercontent.com/17694094/29757325-a10e017a-8bdd-11e7-805d-dbef7f322bad.png)

## Expected Result
No redundant message outputs.

## Test Build
Branch| Commit id | Target Device |Test Date | Result 
---| ---| ---| ---|--- 
master | [6c160b5](https://github.com/01org/zephyr.js/commit/6c160b5d77c32b89e0fd165a644b4cd243d01929) | Arduino 101 | Aug 28, 2017 | Fail

**Comment by brianjjones** [comment] 2017-08-30 17:28
I'm betting its the same thing that causes it to be printed for issue #1458

**Comment by brianjjones** [comment] 2017-08-30 19:43
This will be fixed by #1510

**Comment by qiaojingx** [comment] 2017-09-01 02:49
Verified with commit a0b1217 +#1510， this issue is not reproduced.

**Comment by xiaoyu3x** [comment] 2017-09-20 07:45
This issue will be closed again when PR #1510 is merged.

**Comment by brianjjones** [comment] 2017-10-13 17:09
Looks like #1576 will be the new fix.

**Comment by xiaoyu3x** [comment] 2017-10-17 01:32
Verified with commit [be3ebf7](https://github.com/01org/zephyr.js/pull/1576/commits/be3ebf7c43843a99eb7229d7c3700628de666291)+[dd371e7](https://github.com/01org/zephyr.js/pull/1576/commits/dd371e794c65b3ec61100a61493d29f3c5d512f0) +[#1576](https://github.com/01org/zephyr.js/pull/1576)， this issue is not reproduced.

**Closed** 2017-10-19 15:31 UTC
Labels: bug, P2
