### ISSUE TITLE
[sensor] Error thrown when import custom module or large segment code

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#549] opened 2016-12-15 06:29 UTC
When add a large segment code or import custom module [BMP280.js](https://github.com/01org/zephyr.js/blob/master/modules/BMP280.js) in samples/Accelerometer.js, throw out error.

error log:
```
zjs_sensor_ipm_send_sync: FATAL ERROR, ipm timed out
zjs_sensor_create failed to init
```

**Comment by grgustaf** [comment] 2016-12-15 16:50
@brianjjones, might be wise to git bisect this one and see where it broke. Might have been one of @jimmy-huang's recent patches or my fault again.

**Comment by brianjjones** [comment] 2016-12-16 16:58
@grgustaf This is a race condition.  By adding the BMP280.js, we now have two things trying to init at the same time.  Apparently IPM can't handle this currently, and the sensor IPM times out.  If you wrap the entire Accelerometer.js code with a setTimeout for a second, it works fine.  This may just be a limitation of the IPM system, but perhaps we can do a better job with scheduling them.  I'll dig in more and let you know.

**Comment by brianjjones** [comment] 2016-12-16 20:22
This is solved by https://github.com/01org/zephyr.js/pull/555

**Comment by xiaolongx** [comment] 2016-12-20 07:47
This issue cannot reproduce on Arduino 101 with commit 5a25755

**Comment by grgustaf** [comment] 2016-12-21 20:36
Closing, thanks.

**Closed by grgustaf** 2016-12-21 20:36 UTC
Labels: bug, P1, regression
