### ISSUE TITLE
backspace key isn't handled right in ashell

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#728] opened 2017-02-14 19:02 UTC
For me, it prints <CTRL> 8 or something and seems to hit Enter, etc.

**Comment by brianjjones** [comment] 2017-02-28 19:44
Works for me, what kind of keyboard?

**Comment by qiaojingx** [comment] 2017-03-01 08:07
This issue can be reproduced when using `minicom -D /dev/ttyACM0` to connect ashell with terminal.
Commit: fc06a11

**Comment by brianjjones** [comment] 2017-03-25 00:00
Can someone take a screenshot of this? I've never seen it.  Thanks.

**Comment by qiaojingx** [comment] 2017-03-28 06:55
It seems only reproduced when using `minicom -D /dev/ttyACM0`. Not reproduced when using `screen /dev/ttyACM0 115200`
![selection_005](https://cloud.githubusercontent.com/assets/19813546/24392426/5c029f26-13c6-11e7-86a6-0108738d5e8f.png)

**Comment by brianjjones** [comment] 2017-03-28 21:22
Fix is here https://github.com/01org/zephyr.js/pull/927

**Comment by qiaojingx** [comment] 2017-03-29 03:25
Verified with commit 1c67773 + #927. This issue is not reproducible.
Will close it after patch merged.

**Closed** 2017-04-01 00:53 UTC
Labels: bug, fixed, P2
