### ISSUE TITLE
[buffer] Cannot work for buffer on Linux module and K64 board

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#970] opened 2017-04-05 09:00 UTC
### Description

Cannot work for buffer on Linux module and K64 board. 

Console log(Linux):
`Segmentation fault (core dumped)`

Console log(K64):
```
***** BUS FAULT *****
  Executing thread ID (thread): 0x20004ecc
  Faulting instruction address:  0x1197e
  Imprecise data bus error
Fatal fault in essential thread! Spinning...
```
 

### Test Code

[/samples/Buffer.js](https://github.com/01org/zephyr.js/blob/master/samples/Buffer.js)
[/samples/tests/BufferMemory.js](https://github.com/01org/zephyr.js/blob/master/samples/tests/BufferMemory.js)
[/tests/test-buffer.js](https://github.com/01org/zephyr.js/blob/master/tests/test-buffer.js)
[/tests/test-buffer-rw.js](https://github.com/01org/zephyr.js/blob/master/tests/test-buffer-rw.js)

 

### Actual Result

Throw out error and cannot work.

 

### Expected Result

No error and work well.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | ddcbbb| Linux | April 5, 2017 | Fail
master | ddcbbb| K64 | April 5, 2017 | Fail

**Comment by grgustaf** [comment] 2017-04-05 15:14
@cuiyanx, the error it throws is working according to [your request](https://github.com/01org/zephyr.js/issues/916#issuecomment-290284288) in #946. :) However, I've submitted #966 which should be merged today, which fixes the test to consider that error a "pass".

**Comment by grgustaf** [comment] 2017-04-05 16:49
You listed all those four tests, but I think it was probably only test-buffer.js that failed? That works w/ #966. The other also work for me, on all three platforms: a101, k64f, and linux; but I expect they did before too.

If that's true, it would be nice if you could make your report more specific to the failing test.

**Comment by cuiyanx** [comment] 2017-04-06 01:37
![selection_001](https://cloud.githubusercontent.com/assets/22387607/24733829/9a0c9366-1aac-11e7-8c6a-2e4f389d4841.jpg)

**Comment by cuiyanx** [comment] 2017-04-06 01:56
On K64:
![selection_001](https://cloud.githubusercontent.com/assets/22387607/24734266/02ac2ca4-1aaf-11e7-9a94-600faee594fc.jpg)
![selection_002](https://cloud.githubusercontent.com/assets/22387607/24734267/0308527c-1aaf-11e7-81bf-bf8372e17486.jpg)

**Comment by qiaojingx** [comment] 2017-04-06 05:06
Verified with commit ddcbbbe + #966 on K64F and Linux. This issue is still reproducible.

**Comment by haoxli** [comment] 2017-04-06 05:48
This should be a release block issue which block Buffer API on K64F and Linux.

**Comment by qiaojingx** [comment] 2017-04-06 08:07
This issue is probably caused by #964.
commit 6438700 failed
commit 7bf8e0b pass

**Comment by jimmy-huang** [comment] 2017-04-07 00:44
I can reproduce this, it's the same bug as #988, buffer fails on create

**Comment by grgustaf** [comment] 2017-04-07 01:06
Fixed by #989

**Closed** 2017-04-07 01:12 UTC
Labels: bug, fixed, P2

**Comment by qiaojingx** [comment] 2017-04-07 02:29
Verified with commit f8f9621 on K64f and Linux. This issue is not reproducible.

**Comment by cuiyanx** [comment] 2018-01-10 01:49
Fixed and closed
