### ISSUE TITLE
[GPIO] GPIO doesn't work on FRDM-K64F

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#718] opened 2017-02-13 08:34 UTC
Fail to run GPIO related samples([ButtonLEDs-k64f.js](https://github.com/01org/zephyr.js/blob/master/samples/ButtonLEDs-k64f.js), [Blink-k64f.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/basics/Blink-k64f.js)) and tests([test-k64f-pins.js](https://github.com/01org/zephyr.js/blob/master/tests/test-k64f-pins.js)) on FRDM-K64F with commit 3f8eb85, But it works on Arduino 101.
 
Serial logs:
```
Starting Blink-k64f example...
src/zjs_gpio.c:463 zjs_gpio_init():
[ERROR] cannot find GPIO device 'GPIO_0'
src/zjs_gpio.c:463 zjs_gpio_init():
[ERROR] cannot find GPIO device 'GPIO_1'
src/zjs_gpio.c:463 zjs_gpio_init():
[ERROR] cannot find GPIO device 'GPIO_2'
src/zjs_gpio.cio_init():
[ERROR] cannot find GPIO device 'GPIO_3'
src/zjs_gpio.c:463 zjs_gpio_init():
[ERROR] cannot find GPIO devic (thread): 0x20006a2c
  Faulting instruction address:  0x11f38020
  Instruction bus error
Fatal fault in essential thread! Spinning...
```
Branch | Target Device | Build ID | Date | Result
---|---|---|---|---
master | FRDM-K64F | 21915c0 | Feb 7, 2017 | PASS
master | Arduino 101 | 3f8eb85 | Feb 13,2017 | PASS
master | FRDM-K64F | 3f8eb85 | Feb 13, 2017 | FAIL

**Comment by pfalcon** [comment] 2017-02-13 09:16
Duplicate of https://github.com/01org/zephyr.js/issues/665

**Closed** 2017-02-13 10:06 UTC
