### ISSUE TITLE
clearInterval fails if button press happens too quickly in Spaceship2.js

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#139] opened 2016-08-25 00:39 UTC
If you tap and release the pushbutton in this sample very quickly, you can get the `message:native_clear_interval_handler: timer not found`

If you do it enough times, you can get to where you have two ore more of the timer functions running at once and competing with each other for control of the LEDs.

**Comment by jprestwo** [comment] 2016-10-13 19:24
This is fixed by my ring buffer / callback queue change:
https://github.com/01org/zephyr.js/pull/287

This PR is in very early stages. We need to figure out if we want to use both pre/post callbacks AND ring buffer, or just the ring buffer.

Another thing with this issue is that is not entirely related to callbacks. The Zephyr GPIO driver will sometimes trigger twice at the same level when using rising and falling edge detection. This causes the top if block to get called two times in a row, and in turn never clearing the interval. The fix for this is to check if the timer is null, and set it to null after clearing it. This provides the needed synchronization.

**Comment by grgustaf** [comment] 2016-11-02 21:12
Doing some more testing, I see with a Grove touch sensor as my button I can't seem to reproduce the problem. With a Grove pushbutton, it's very easy to reproduce. Perhaps the touch sensor is hardware debounced?

**Comment by xiaolongx** [comment] 2016-11-15 08:55
This issue cannot reproduce on Arduino 101 with commit 2ff271b.

**Closed** 2016-12-05 17:25 UTC
