### ISSUE TITLE
[REG] Buffer tests no longer work

### ISSUE THREAD

**Issue by brianjjones** [01org/zephyr.js#524] opened 2016-12-09 01:17 UTC
The files tests/test-buffer.js and tests/test-buffer-rw.js no longer run, I just get a "JerryScript: cannot run javascript" error.  This was tested on master using both an Arduino101 and FRDM-K64 board.

**Comment by xiaolongx** [comment] 2016-12-09 03:26
This issue also occurs on samples/Buffer.js and samaples/tests/BufferMemory.js using both Arduino101 and FRDM_K64F.

Branch | Build ID | Result
---|---|---
master | d4e1d64 | PASS
master | dc703a1 | FAIL

**Comment by grgustaf** [comment] 2016-12-09 16:23
@xiaolongx, these tables of last known PASS and FAIL are very helpful, thank you. If you guys are ever bored, you're welcome to git bisect to find the exact patch that broke the condition. :) But again this is awesome and lets me easily do that.

**Comment by grgustaf** [comment] 2016-12-13 17:02
Hmm, interesting that you filed this, @brianjjones, because I just git bisected this to your commit dc703a1. :)

**Comment by grgustaf** [comment] 2016-12-13 19:34
Fixed with #535.

**Comment by xiaolongx** [comment] 2016-12-14 01:40
This issue cannot reproduce on both Arduino 101 and FRDM-K64F after #535 merged.

**Closed** 2016-12-14 18:22 UTC
Labels: bug, fixed, P1, regression
