### ISSUE TITLE
[Buffer] length is not a readonly attribute

### ISSUE THREAD

**Issue by haoxli** [01org/zephyr.js#172] opened 2016-09-12 12:06 UTC
`readonly attribute unsigned long length;`

In [buffer.md](https://github.com/01org/zephyr.js/blob/master/docs/buffer.md), the length of Buffer should be readonly, but actually it can be modified.

```
var buff = new Buffer(8);
var original = buff.length;
buff.length = buff.length + 1;
print(original);
print(buff.length);
```

The print result is 9, not the expected 8.

**Comment by jimmy-huang** [comment] 2016-10-27 17:24
this is probably a limitation of jerryscript, there's not a way for us to set a read-only attribute on any js objects, at least I am not aware of any, @brianjjones?

**Comment by pfalcon** [comment] 2016-10-27 17:35
Quick grep over JrS codebase:

~~~
  length_prop_value_p = ecma_create_named_data_property (obj_p,
                                                         length_magic_string_p,
                                                         ECMA_PROPERTY_FLAG_WRITABLE,
                                                         NULL);
~~~

(read-only should be "not writable" in javascript-speak).

**Comment by jimmy-huang** [comment] 2016-10-27 18:23
@pfalcon thanks for pointing that out, but ecma_ are internal apis, not the public apis we can use, we should file a feature request to have a jerry_ api to allow setting the property

**Comment by grgustaf** [comment] 2016-12-23 00:02
Fixed by PR #576. This makes test-buffer.js pass all 18/18 subtests.

**Comment by grgustaf** [comment] 2016-12-23 00:03
BTW @jimmy-huang and @pfalcon, I found that this and more can be done using jerry_define_own_property.

**Comment by xiaolongx** [comment] 2017-01-10 01:41
This issue cannot reproduce on both Arduino 101 and FRDM-K64F with commit 2345f96.

**Closed** 2017-01-10 05:07 UTC
Labels: bug, fixed, P2
